source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.7'
gem 'rails-i18n', '~> 4.0.3'
gem 'activemodel', '~> 4.1.7'

gem 'localeapp', github: 'alex-klepa/localeapp', branch: 'master'
gem 'cached_key_value_store'

gem 'ohm', '~> 2.0.1'
gem 'ohm-contrib', '~> 2.0.0'
gem 'msgpack', '~> 0.5.11'
gem 'redis-rails', '~> 4.0.0'
gem 'redis-session-store', '~> 0.7.0'
gem 'mlanett-redis-lock', require: 'redis-lock'
gem 'sidekiq', '~> 3.2.1'
gem 'sinatra', '~> 1.4.5', :require => nil
gem 'browser', '~> 0.7.0'
gem 'gibberish', '~> 1.4.0'
gem 'actionpack-action_caching', '~> 1.1.0'
gem 'cacheable_flash', '~> 0.3.3'

gem 'mercury-rails', github: 'alex-klepa/mercury'
# gem 'mercury-rails', path: '/Users/sash/apps/mercury'


gem 'simple_form', '~> 3.0.2'
gem 'rails_12factor', '~> 0.0.2', group: [:production, :staging]

#gem 'rack-mini-profiler', group: [:staging, :development]

gem 'bootstrap-sass', '~> 3.2.0'
gem 'sass-rails', '~> 4.0.3'
gem 'autoprefixer-rails', '~> 2.0.0.20140622'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use Uglifier as compressor for JavaScript assets
gem 'htmlcompressor', '>= 0.2.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'coffee-script-source', '~> 1.8.0'
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails', '~> 3.1.1'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks', '~> 2.2.2'

gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'ruby_regex'

gem 'bluepill', '~> 0.0.68'

group :development, :test do
  gem "figaro"
  gem 'pry'
  gem "thin"
#  gem 'spring'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'mocha'             # https://github.com/freerange/mocha
  gem 'byebug'            # https://github.com/deivid-rodriguez/byebug, http://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-byebug-gem
  gem 'minitest-focus'    # https://github.com/seattlerb/minitest-focus
end

gem 'rack-mini-profiler', require: false

gem 'database_cleaner'

gem 'godzilla_api', git: 'https://08689d5df765820f69c96ccae7db9ecaed88f27e:x-oauth-basic@github.com/digitalmedia/godzilla_api.git', branch: 'master'
# gem 'godzilla_api', path: '/Users/sash/apps/godzilla_api', branch: 'develop'


gem 'thread_local_accessor', '~> 0.1.1'

gem 'unicorn'
gem 'newrelic_rpm'
ruby '2.2.2'

